baseURL: 'http://example.org/'
languageCode: 'es'
title: 'Proyecto Hugo'
theme: "colordrop" 

params: 
  description: Bienvenido al sitio web de A. J. Aragón sobre el software Hugo.
  siteLogo: "/arbol_logo.jpg"

languages:
  en:
    languageName: English
    weight: 1

  es:
    languageName: Español
    weight: 2
    
  fr:
    languageName: Français
    weight: 3
   