baseURL: 'http://example.org/'
languageCode: 'es'
title: 'Proyecto Hugo'
theme: "colordrop" 

languages:
  en:
    languageName: English
    weight: 1

  es:
    languageName: Español
    weight: 2
    
  fr:
    languageName: Français
    weight: 3
   